CREATE TABLE sales (
row_id INT PRIMARY KEY,
order_id VARCHAR(20), 
order_date DATE, 
ship_date DATE, 
ship_mode VARCHAR(20),
customer_id VARCHAR(50), 
customer_name VARCHAR(50), 
segment VARCHAR(20), 
country VARCHAR(20), 
city VARCHAR(20), 
state VARCHAR(20),
postal_code INT, 
region VARCHAR(20), 
product_id VARCHAR(50), 
category VARCHAR(20), 
sub_category VARCHAR(30),
product_name VARCHAR(200), 
sales DECIMAL(10,2), 
quantity INT, 
discount DECIMAL(10,2), 
profit DECIMAL(10,2),
total_sales DECIMAL(10,2)
);